### ISSUE TITLE
Test curves against well-known outputs

### ISSUE THREAD

**Issue by k0001** [adjoint-io/elliptic-curve#5]
Hi, I came across this nice library, took a look at the tests, and I wondered: Wouldn't it be a good idea to test each curve against some well-known outputs in a “golden test” kind of way? Mostly to ensure that the curves are defined using the correct parameters, and that it stays that way over time. Thanks!

**Comment by sdiehl** [comment]
Given that the curves are fairly standardised mathematical objects, there's only about 6 parameters that are actually needed to construct the equations involved i.e. the (the generator point, the field modulus, etc) it's unlikely that a randomly chosen set of parameters satisfies all the property tests.

There are however some test vectors for the commonly used curves that could be added. 

* http://point-at-infinity.org/ecc/nisttv
* https://tools.ietf.org/html/rfc8032.html#section-7.1
* https://tools.ietf.org/id/draft-yonezawa-pairing-friendly-curves-01.html#rfc.appendix.B
* https://tools.ietf.org/html/rfc7027#appendix-A.1
* https://tools.ietf.org/html/rfc8032#section-7.1

We're certainly open to enriching the test suite to make it more robust and trusted.

**Comment by sdiehl** [comment]
The library now has several thousand tests. Probably going to close this as there isn't much need to test more.
